train:
  id: ${task}
  size: ${img_size}
  frame_skip: 2
  frame_stack: ${frame_stack}
  num_envs: 1

test:
  id: ${task}
  size: ${img_size}
  frame_skip: 2
  frame_stack: ${frame_stack}
  num_envs: 1

