_target_: agent.AgentConfig

denoiser: null


upsampler: null

# rew_end_model: null
rew_end_model: null

actor_critic_cfg: 
  _target_: rl_agent.baseagent.ActorCriticConfig
  type: ${ac_type}
  feature_dim: 512
  hidden_dim: 256
  img_size: ${env.train.size}
  num_actions: ???
  num_states: ???
  depth: 3
  acitive_fn: 'tanh'
  online_lr: 3e-6
  frame_stack: 1

ppo_cfg:
  _target_: models.rl_agent.baseagent.PPOConfig
  mini_batch_size: 256
  clip_param: 0.2
  K_epochs: 10
  max_grad_norm: 0.5
  adv_compute_mode: 'iql' 
  use_adam_eps: True
  use_std_share_network: False
  use_state_norm: True
  use_lr_decay: True