_target_: agent.AgentConfig

denoiser: null


upsampler: null

# rew_end_model: null
rew_end_model: null

actor_critic_cfg: 
  _target_: rl_agent.baseagent.ActorCriticConfig
  type: ${ac_type}
  feature_dim: 50
  hidden_dim: 1024
  img_size: ${env.train.size}
  num_actions: ???
  num_states: ???
  depth: 3
  acitive_fn: 'relu'
  online_lr: 3e-6
  frame_stack: ${frame_stack}
  image_size: ${img_size}
  use_trunk: ${use_trunk}
  trunk_ln: True
  trunk_activation: 'tanh'

ppo_cfg:
  _target_: models.rl_agent.baseagent.PPOConfig
  mini_batch_size: 64
  clip_param: 0.2
  K_epochs: 10
  max_grad_norm: 0.5
  adv_compute_mode: 'gae' 
  use_adam_eps: True
  use_std_share_network: False
  use_state_norm: True
  use_lr_decay: True
  use_bc: True

drqv2_cfg:
  __target__: DrQv2Config
  critic_target_tau: 0.01
  num_expl_steps: 2000
  update_every_steps: 2
  stddev_clip: 0.3
  use_data_aug: true
  encoder_lr_scale: 1
  stage2_update_encoder: true
  stage2_std: 0.1
  stage3_update_encoder: true
  std0: 1.0
  std1: 0.1
  std_n_decay: 500000
  utd_ratio: 1
  mini_batch_size: 512
  num_critics: 2
  offline_data_ratio: 0.5

